# ================= ???? (DEV) ???? =================
# ???? MySQL?????????????? (RAM)
spring.datasource.url=jdbc:h2:mem:dorm_system_dev;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ?? JPA ???????????????????????????????
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# ????????? 8080 ??
server.port=8080